        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 19 09:05:42 2019
        MODULE ABOUND__genmod
          INTERFACE 
            SUBROUTINE ABOUND
            END SUBROUTINE ABOUND
          END INTERFACE 
        END MODULE ABOUND__genmod
