        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 19 09:05:42 2019
        MODULE COMBINE__genmod
          INTERFACE 
            SUBROUTINE COMBINE
            END SUBROUTINE COMBINE
          END INTERFACE 
        END MODULE COMBINE__genmod
