        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 19 09:05:42 2019
        MODULE CREATDIRECTORY__genmod
          INTERFACE 
            SUBROUTINE CREATDIRECTORY(FOLDER_NAME)
              CHARACTER(LEN=200) :: FOLDER_NAME
            END SUBROUTINE CREATDIRECTORY
          END INTERFACE 
        END MODULE CREATDIRECTORY__genmod
