        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 19 09:05:42 2019
        MODULE LIPYEAR__genmod
          INTERFACE 
            SUBROUTINE LIPYEAR(MYEAR,T_DAY)
              INTEGER(KIND=4) :: MYEAR
              INTEGER(KIND=4) :: T_DAY
            END SUBROUTINE LIPYEAR
          END INTERFACE 
        END MODULE LIPYEAR__genmod
