        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 19 09:05:42 2019
        MODULE MONTHDAY_TO_JULIANDAY__genmod
          INTERFACE 
            SUBROUTINE MONTHDAY_TO_JULIANDAY(I,KKYEAR,K,NNNPRNT,        &
     &JDAY_FIELD)
              INTEGER(KIND=4) :: I
              INTEGER(KIND=4) :: KKYEAR
              INTEGER(KIND=4) :: K
              INTEGER(KIND=4) :: NNNPRNT
              INTEGER(KIND=4) :: JDAY_FIELD
            END SUBROUTINE MONTHDAY_TO_JULIANDAY
          END INTERFACE 
        END MODULE MONTHDAY_TO_JULIANDAY__genmod
