        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 19 09:05:42 2019
        MODULE SETUP__genmod
          INTERFACE 
            SUBROUTINE SETUP
            END SUBROUTINE SETUP
          END INTERFACE 
        END MODULE SETUP__genmod
