        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb 19 09:05:42 2019
        MODULE VOLUME__genmod
          INTERFACE 
            SUBROUTINE VOLUME(MBOT)
              INTEGER(KIND=4) :: MBOT
            END SUBROUTINE VOLUME
          END INTERFACE 
        END MODULE VOLUME__genmod
